version: "3.8"

services:
  database:
    container_name: database
    image: postgres:15.4
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/inahef
    ports:
      - "54322:5432"

  # redis:
  #   container_name: redis
  #   image: redis:7.2-alpine
  #   restart: always
  #   ports:
  #     - '6379:63799'
  #   command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  #   volumes:
  #     - redis:/data

volumes:
  postgres:
  redis:
